#// simple c program (Hello world) ,single line comment
/*
Name: David Gichuki
Reg: CT100/G/26130/25
Description: Hello world program
*/

#include<stdio.h>
//main function
int main(){
	printf("BIT YEAR1 SEM1 UNITS \n");
	printf(" 1.SPH2107 ANALOGUE ELECTRONICS \n 2.SPI2102 COMPUTER SYSTEM AND ORGANIZATION \n 3.UCU2105 FUNDAMENTALS OF ICT \n 4.SPI2103 INTRODUCTION TO COMPUTER APPLICATIONS \n 5.SPI2120 ESSENTIALS OF ACCOUNTING \n 6.UCU2106 COMMUNICATION SKILLS AND LITERACY \n 7.SPM2104 MATHEMATICS FOR SCIENCE \n 8.SPI2101 INTRODUCTION TO PROGRAMMING AND ALGORITHMS");
	return 0;
}	